# https://github.com/marketplace/actions/github-pull-request-action
# https://github.com/marketplace/actions/slack-notify-pull-request
# https://github.com/marketplace/actions/slack-pr-open-notification

name: pull request
on:
  push:
    branches:
      - "feature/*" # Support wildcard matching
  pull_request:
    types: [opened, reopened]

jobs:
  slack-notification:
    if: ${{ always() }}
    # needs: [pull-request]
    runs-on: ubuntu-latest
    steps:
      # - name: Set TEST_VALUE_1 Env Variable
      #   run: |
      #     TEST_VALUE_1="ðŸ§‘ðŸ»â€ðŸ’» TEST"
      #     echo "TEST_VALUE_1=${TEST_VALUE_1}" >> $GITHUB_ENV
      #     echo "--------------------------------------------------------"
      #     echo ${{ needs.pull-request.result }}
      - name: slack-send
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }},
              PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }},
              PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }},
              PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }},
              PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }},
              PULL_REQUEST_BODY : ${{ github.event.pull_request.body }},
              PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }},
              PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }},
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CUSTOM }}
          ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
# SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL }}
# PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
# PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
# PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
# PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }}
# PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
# PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
# PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }}
# PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }}
