name: pull request
on: pull_request

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: view the PR number
        run: |
          echo "PR number : ${{ github.event.pull_request.number }}"
          echo "title : ${{ github.event.pull_request.title }}"
          echo "author : ${{ github.event.pull_request.user.login }}"
          echo "avatar_url : ${{ github.event.pull_request.user.avatar_url }}"
          echo "html_url : ${{ github.event.pull_request.html_url }}"
          echo "body : ${{ github.event.pull_request.body }}"
          echo "head.ref : ${{ github.event.pull_request.head.ref }}"
          echo "base.ref : ${{ github.event.pull_request.base.ref }}"
      - name: slack-send
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "PULL_REQUEST_NUMBER" : "${{ github.event.pull_request.number }}",
              "PULL_REQUEST_TITLE" : "${{ github.event.pull_request.title }}",
              "PULL_REQUEST_AUTHOR_NAME" : "${{ github.event.pull_request.user.login }}",
              "PULL_REQUEST_AUTHOR_ICON_URL" : "${{ github.event.pull_request.user.avatar_url }}",
              "PULL_REQUEST_URL" : "${{ github.event.pull_request.html_url }}",
              
              "PULL_REQUEST_COMPARE_BRANCH_NAME" : "${{ github.event.pull_request.head.ref }}",
              "PULL_REQUEST_BASE_BRANCH_NAME" : "${{ github.event.pull_request.base.ref }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CUSTOM }}
          ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"



# "PULL_REQUEST_BODY" : "${{ github.event.pull_request.body }}",