# https://github.com/marketplace/actions/github-pull-request-action

name: pull request
on:
  push:
    branches:
      - "feature/*" # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "" # If blank, default: triggered branch
          destination_branch: "main" # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*" # Full markdown support, requires pr_title to be set
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md" # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "wei,worker" # Comma-separated list (no spaces)
          pr_assignee: "wei,worker" # Comma-separated list (no spaces)
          pr_label: "auto-pr" # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1" # Milestone name
          pr_draft: true # Creates pull request as draft
          pr_allow_empty: true # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   destination_branch: "develop"
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: output-url
        run: echo ${{ steps.open-pr.outputs.pr_url }}
      - name: output-number
        run: echo ${{ steps.open-pr.outputs.pr_number }}
      - name: output-has-changed-files
        run: echo ${{ steps.open-pr.outputs.has_changed_files }}
      - name: check-values
        run: echo ${{ steps.open-pr }}

  # slack-notification:
  #   if: ${{ always() }}
  #   needs: [pull-request]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set TEST_VALUE_1 Env Variable
  #       run: |
  #         TEST_VALUE_1="ðŸ§‘ðŸ»â€ðŸ’» TEST"
  #         echo "TEST_VALUE_1=${TEST_VALUE_1}" >> $GITHUB_ENV
  #         echo "--------------------------------------------------------"
  #         echo ${{ needs.pull-request }}
  #     - name: slack-send
  #       uses: slackapi/slack-github-action@v1.19.0
  #       with:
  #         payload: |
  #           {
  #             "test_value_1": "${{ env.TEST_VALUE_1 }}"
  #           }
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CUSTOM }}
  #         ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
